# Generated by Django 3.2.6 on 2021-10-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='link',
            new_name='silka',
        ),
    ]
