# Generated by Django 3.2.6 on 2021-10-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_link_aboutmodel_silka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='silka',
            new_name='link',
        ),
    ]
