# Generated by Django 3.2.6 on 2021-10-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_silka_aboutmodel_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='link',
        ),
    ]
