# Generated by Django 3.2.6 on 2021-10-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20211018_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AboutModel',
        ),
        migrations.DeleteModel(
            name='FutureImage',
        ),
        migrations.DeleteModel(
            name='FutureModel',
        ),
        migrations.DeleteModel(
            name='ServiceModel',
        ),
    ]
